### ISSUE TITLE
Update moviepilot.de URLs to https

### ISSUE THREAD

**Issue by nrenner** [kevgaar/MoviePilot-Rating-Extension#1]
moviepilot.de switched to https a while ago and redirects http URLs, so the UserScript URL patterns no longer match and the script is not executed.

**Comment by kevgaar** [comment]
Was wondering some time ago why it wasn't working anymore and had no leisure to figure it out. Shame on me.

Thanks you very much!
Is fixed and is going to be rolled out on your next Greasemonkey/Tampermonkey update! :-)
